stages:
  - containerization
  - deployment

variables:
  APPLICATION_NAME: cms-front
  DOCKER_IMAGE: ${DOCKER_HUB_USERNAME}/${APPLICATION_NAME}

image: moreillon/ci-dind
services:
  - name: docker:19.03.12-dind


containerization:
  stage: containerization
  tags:
    - dind
  script:
    # Docker hub login
    - echo "${DOCKER_HUB_PASSWORD}" | docker login --username ${DOCKER_HUB_USERNAME} --password-stdin
    # Building the container image
    - docker build -t ${DOCKER_IMAGE} .
    # Pushing the image to the registry
    - docker push ${DOCKER_IMAGE}
    # Cleanup
    - docker image rm ${DOCKER_IMAGE}

deployment:
  stage: deployment
  tags:
    - dind
  script:
    # create/update the deployment
    - envsubst < kubernetes/deployment.yml | kubectl apply -f -

    # If a nodeport is specified, serve app through a nodeport service
    - >
      if [ -z ${SERVICE_PORT} ];
      then echo "SERVICE_PORT not set, skipping creation of NodePort service";
      else envsubst < kubernetes/nodeport_service.yml | kubectl apply -f -;
      fi

    # if a domain name is specified, serve app through an ingress
    - >
      if [ -z ${CERTIFICATE_DOMAIN} ];
      then echo "CERTIFICATE_DOMAIN not set, skipping creation of ingress";
      else envsubst < kubernetes/ingress.yml | kubectl apply -f -;
      fi

    # Pull latest image of deployment
    - kubectl rollout restart deployment/${APPLICATION_NAME}
  environment:
    name: production
    kubernetes:
      namespace: ${KUBERNETES_NAMESPACE} # Obtained from GitLab
