apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cms-front
  template:
    metadata:
      labels:
        app: cms-front
    spec:
      containers:
      - name: cms-front
        image: ${CONTAINER_REGISTRY}/cms-front
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: cms-front
  name: cms-front
spec:
  ports:
  - port: 80
    nodePort: ${SERVICE_PORT}
  selector:
    app: cms-front
  type: LoadBalancer
