apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APPLICATION_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APPLICATION_NAME}
  template:
    metadata:
      labels:
        app: ${APPLICATION_NAME}
    spec:
      containers:
        - name: ${APPLICATION_NAME}
          image: ${CONTAINER_IMAGE_TAGGED}
          ports:
            - containerPort: 3000
          env:
            - name: NUXT_PUBLIC_API_BASE
              value: https://api.articles.maximemoreillon.com
            - name: NUXT_PUBLIC_LOGIN_URL
              value: https://api.users.maximemoreillon.com/auth/login
            - name: NUXT_PUBLIC_IDENTIFICATION_URL
              value: https://api.users.maximemoreillon.com/users/self
            - name: NUXT_PUBLIC_IMAGE_MANAGER_API_URL
              value: https://img.maximemoreillon.com
            - name: NUXT_PUBLIC_CANONICAL_URL
              value: https://articles.maximemoreillon.com

---
apiVersion: v1
kind: Service
metadata:
  name: ${APPLICATION_NAME}
spec:
  type: ClusterIP
  selector:
    app: ${APPLICATION_NAME}
  ports:
    - port: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ${APPLICATION_NAME}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - cms.maximemoreillon.com
        - articles.maximemoreillon.com
      secretName: ${APPLICATION_NAME}
  rules:
    - host: cms.maximemoreillon.com
      http:
        paths:
          - path: /
            backend:
              serviceName: ${APPLICATION_NAME}
              servicePort: 3000
    - host: articles.maximemoreillon.com
      http:
        paths:
          - path: /
            backend:
              serviceName: ${APPLICATION_NAME}
              servicePort: 3000
